In [1]:
import cv2
import os
import os.path as osp
import numpy as np
import torch

In [5]:
lr = 0.00006
warmup_iters = 1500
warmup_ratio = 1e-6
power = 1.0
min_lr = 0.0
start_lr = lr * warmup_ratio
step = (lr-start_lr)/warmup_iters
start_lr, step, start_lr + step*49

(6e-11, 3.999996e-08, 1.96005804e-06)

In [2]:
path = r'show_dir/34.png'
img = cv2.imread(path)
img.dtype, img.shape, np.unique(img)

(dtype('uint8'), (1024, 1024, 3), array([  0, 255], dtype=uint8))

In [10]:
a = np.array([98.73, 0.85, 0.39, 0.04])
b = 1 / a
c = b/b.sum()
a, b, c, c.sum()

(array([9.873e+01, 8.500e-01, 3.900e-01, 4.000e-02]),
 array([1.01286336e-02, 1.17647059e+00, 2.56410256e+00, 2.50000000e+01]),
 array([3.52291701e-04, 4.09197173e-02, 8.91839992e-02, 8.69543992e-01]),
 1.0)

In [3]:
a = dict(asd=1, we=2)

In [6]:
a.get('asd', []), a.get('sdf', [])

(1, [])

In [5]:
path = r'/home/csl/code/rsaicp_CD/data/ade/ADEChallengeData2016/annotations/training/ADE_train_00000011.png'
a = cv2.imread(path, -1)

In [6]:
a.shape

(247, 356)