In [7]:
import cv2
import os
import os.path as osp
import numpy as np
import torch

In [10]:
a = np.array([98.73, 0.85, 0.39, 0.04])
b = 1 / a
c = b/b.sum()
a, b, c, c.sum()

(array([9.873e+01, 8.500e-01, 3.900e-01, 4.000e-02]),
 array([1.01286336e-02, 1.17647059e+00, 2.56410256e+00, 2.50000000e+01]),
 array([3.52291701e-04, 4.09197173e-02, 8.91839992e-02, 8.69543992e-01]),
 1.0)

In [3]:
a = dict(asd=1, we=2)

In [6]:
a.get('asd', []), a.get('sdf', [])

(1, [])

In [5]:
path = r'/home/csl/code/rsaicp_CD/data/ade/ADEChallengeData2016/annotations/training/ADE_train_00000011.png'
a = cv2.imread(path, -1)

In [6]:
a.shape

(247, 356)